# Generated by Django 3.1.4 on 2021-01-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azbankgateways", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="bank_type",
            field=models.CharField(
                choices=[
                    ("BMI", "BMI"),
                    ("SEP", "SEP"),
                    ("ZARINPAL", "Zarinpal"),
                    ("IDPAY", "IDPay"),
                    ("ZIBAL", "Zibal"),
                    ("BAHAMTA", "Bahamta"),
                ],
                max_length=50,
                verbose_name="Bank",
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting"),
                    ("REDIRECT_TO_BANK", "Redirect To Bank"),
                    ("RETURN_FROM_BANK", "Return From Bank"),
                    ("CANCEL_BY_USER", "Cancel By User"),
                    ("EXPIRE_GATEWAY_TOKEN", "Expire Gateway Token"),
                    ("EXPIRE_VERIFY_PAYMENT", "Expire Verify Payment"),
                    ("COMPLETE", "Complete"),
                    ("ERROR", "Unknown error acquired")
                ],
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
